image:
  repository: hyperledger/fabric-tools
  tag: 1.4.6

persistence:
  enabled: false

logging:
  level: debug

peer:
  mspID: OrdererMSP
  tls:
    server:
      enabled: false
    client:
      enabled: false

secrets:
  peer:
    caCert: ordererorg-cacert
    cert: ordererorg-admincert
    key: ordererorg-adminkey
  channels:
    - hlf--channel
  adminCert: ordererorg-admincert
  adminKey: ordererorg-adminkey
  ordTlsRootCert: hlf--ord1-tls-rootcert