image:
  tag: 1.4.6
  
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  path: /
  hosts:
    # TODO: Change this back
    - org1-ca.dev.ncp-hlf.ga
  tls:
    - secretName: org1-ca-tlsrootcert
      hosts:
        # TODO: Change this back
        - org1-ca.dev.ncp-hlf.ga

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi

postgresql:
  enabled: false

mysql:
  enabled: false

config:
  debug: true
  tls: true
  mountTLS: true
  hlfToolsVersion: 1.4.6
  csr:
    names:
      c: KR
      st: Gyeonggi-do
      l: Seongnam-si
      o: "NBP"
      ou: "Blockchain"
  affiliations:
    org1: []